FROM openjdk:17

# Simply the artifact path
ARG artifact=target/spring-boot-web.jar

WORKDIR /opt/app

COPY ${artifact} app.jar

# EXPOSE the port that the Spring Boot app will run on (e.g., 8081 instead of 8080)
EXPOSE 8081

# Set the Java argument to use port 8081, you can change this to any other port if needed
ENTRYPOINT ["java", "-jar", "app.jar", "--server.port=8081"]
